[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hybrid-element-retriever"
version = "0.1.0"
description = "HER: Natural-language to unique, resilient UI locators with verification/self-heal"
readme = "README.md"
requires-python = ">=3.9"
authors = [{name="HER Maintainers"}]
dependencies = [
  "playwright>=1.43",
  "numpy>=1.23",
  "onnxruntime>=1.15; extra == \"cpu\"",
]

[project.optional-dependencies]
dev = [
  "black>=23.0.0",
  "flake8>=6.0.0",
  "mypy>=1.0.0",
  "pytest>=7.3.0",
  "pytest-cov>=4.0.0",
  "pytest-timeout>=2.1.0",
  "pytest-xdist>=3.3.1",
]

[project.scripts]
her = "her.cli:main"
